// demo/vue3/src/App.vue
<template>
  <div>
      <n-button v-show="!viewer" @click="setProps('lang')">切换语言(当前{{options.lang}})</n-button>
      <n-button v-show="!viewer" @click="setProps('theme')">切换主题({{options.theme}})</n-button>
      <n-button v-show="!viewer" @click="designer.panelShow()">属性面板显隐</n-button>
      <n-button @click="viewer = true; mode = false">->流程图</n-button>
      <n-button v-show="viewer" @click="mode = true">活动流程图</n-button>
      <n-button v-show="viewer" @click="viewer = false">流程设计器</n-button>
      <solon-flow-designer ref="designer" v-if="!viewer" v-model="value" :theme="theme" :lang="lang" :type="options.type" :height="95"/>
      <solon-flow-viewer v-if="viewer" :mode="mode"/>
  </div>
</template>
<script setup lang="ts">
import { ref } from "vue";
import { NButton } from "naive-ui";
import { SolonFlowDesigner, SolonFlowViewer } from "./components";

const value = ref<string>('');
const viewer = ref<boolean>(false);
const mode = ref<boolean>(false);
const designer = ref();

const options = ref<{ theme: "light" | "dark"; lang: "en" | "zh", type: "yaml" | "json" }>({
    theme: 'light',
    lang: 'zh',
    type: 'yaml',
});
const theme = ref<"light" | "dark">('light');
const lang = ref<"en" | "zh">('zh');

const setProps = (type: "theme" | "lang") => {
    if (type === "theme") {
        theme.value = theme.value === 'dark' ? 'light' : 'dark';
    }else {
        lang.value = lang.value === 'zh' ? 'en' : 'zh'
    }
}

</script>
<style scoped>
</style>

// demo/react/src/App.tsx
import React from 'react';
import { SolonFlowDesignerRef, SolonFlowDesigner } from './components';
import { Button, Space } from "antd";
import Viewer from "./Viewer.tsx";
import { xmlStr } from "./default.ts";

const App: React.FC = () => {

    const ref = React.useRef<SolonFlowDesignerRef>(null);
    const [value, setValue] = React.useState<string>(xmlStr);
    const [options, setOptions] = React.useState<{ theme: "light" | "dark"; lang: "en" | "zh", type: "yaml" | "json" }>({
        theme: 'light',
        lang: 'zh',
        type: 'yaml',
    });

    const [viewer, setViewer] = React.useState<boolean>(false);
    const [mode, setMode] = React.useState<boolean>(false);

    return <div>
        {!viewer && <Space.Compact title="设计器">
            <Button onClick={() => setOptions({ ...options, lang: options.lang === 'en' ? 'zh' : 'en' })}>切换语言</Button>
            <Button onClick={() => setOptions({ ...options, theme: options.theme === 'dark' ? 'light' : 'dark' })}>切换主题</Button>
            <Button onClick={() => ref.current?.panelShow()}>属性面板显隐</Button>
        </Space.Compact>}
        <Space.Compact title="流程图">
            <Button onClick={() => {
                setViewer(true);
                setMode(false);
            }} type="dashed">普通流程图</Button>
            <Button onClick={() => setMode(true)} type="dashed">活动流程图</Button>
            {viewer && <Button type="dashed" onClick={() => setViewer(false)}>流程设计器</Button>}
        </Space.Compact>
        { viewer ? <Viewer mode={mode}/> : <SolonFlowDesigner
            ref={ref}
            value={value}
            onChange={(value: any) => {
                setValue(value)
            }}
            height={92}
            lang={options.lang}
            theme={options.theme}
            type={options.type} /> }

    </div>;
}

export default App
